### ISSUE TITLE
Hello, why i did not get any token in my address? i fill the google form for a long time .

### ISSUE THREAD

**Issue by suzumiya2014** [zenchainprotocol/zenchain#11]
root@zenchain:~# zenchaind query bank balances zen1039an5r06ljzr826yu2lw59fpu2dn3fwa4uxud
balances: []
pagination:
  next_key: null
  total: "0"

my address is zen1039an5r06ljzr826yu2lw59fpu2dn3fwa4uxud.
I finished the form 8 days ago.
And my node is working since that time, never stop.
But i got no balance in my address, can not start my validator.
I asked in the telegram channel, but no one give me a reply.
That  really make me sad.

**Comment by jovezen** [comment]
Sent
